version: '3.7'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /Users/bill/coding_programme/reddit/tmp/db:/var/lib/mysql/
    ports:
      - "3306:3306"
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - /Users/bill/coding_programme/reddit:/myapp
    ports:
      - '3035:3035'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /Users/bill/coding_programme/reddit:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
